### ISSUE TITLE
Сделать бота

### ISSUE THREAD

**Issue by MaxMakela** [TheDimmGit/price_monitor#1]
### Функционал бота:
- Принимать от пользователя строку (пока что любую)
- Добавлять строку в базу данных
- По запросу пользователя (допустим если он напишет "+") выдать ему все строки которые он до этого записал
Для реализации такого функционала нужно хранить в таблице строку и id чата из которого эта строка была получена. В коде бота нужно проверять полученную строку, если строка равна "+" то нужно сделать выборку из базы всех записей, у которых поле chat_id равен id того чата в котором этот плюс написали и вывести эти строки.

### TODO:

- [x] Создать бот и делать принт всех строк и id текущего чата.
- [x] Убедится что для разных пользователей указывается разный id, для одно и того же - одинаковый.
- [ ] Создать базу с таблицей, в которой есть два поля (chat_id, str).
- [ ] Записывать строки и id чата в базу (написать отдельную функцию, в которая будет принимать эти два параметра и писать их в базу). 
- [ ] Сделать функцию выборки принимающую в качестве параметра chat_id и возвращающую список строк добавленную этим чатом.
Логика работы бота и логика записи в базу должны быть разделены и находится в разных модулях.
